version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass-rails
    versions:
    - 6.0.0
  - dependency-name: spring
    versions:
    - 2.1.1
  - dependency-name: nokogiri
    versions:
    - 1.11.3
